version: "3.9"
services:
    pkg:
        build: .
        ports:
            - "5002:5002"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
          - sqlvolume:/var/opt/mssql

        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1434:1433"
volumes:
  sqlvolume: